apiVersion: v1
kind: ConfigMap
metadata:
  name: arthas-center-cm
data:
  SELF_HOST: "arthas-center-svc.default.svc.cluster.local"
  AGENT_INIT_SHELL_DOWN_URL: "http://192.168.3.47:5244/d/local/as-agent.sh"
  AGENT_TAR_DOWN_URL: "http://192.168.3.47:5244/d/local/as-agent.tar.gz"
  AGENT_PORT: "13736"