{{- if .Values.nginx.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arthas-center.fullname" . }}-nginx-conf
data:
  nginx.conf: |
    worker_processes  4;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
{{- end }}