{{- if .Values.nginx.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arthas-center.fullname" . }}-nginx-default-conf
data:
  default.conf: |
    server {
    listen 8080;

    location /api {
        proxy_pass http://{{ include "arthas-center.fullname" . }}-svc:{{ .Values.service.server.http.port }};
    }

    location / {
        proxy_pass http://{{ include "arthas-center.fullname" . }}-web-svc:{{ .Values.service.web.http.port }};
    }

    location /ws {
        proxy_pass http://{{ include "arthas-center.fullname" . }}-svc:{{ .Values.service.server.ws.port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    }
{{- end }}