apiVersion: v1
kind: Service
metadata:
  name: {{ include "arthas-center.fullname" . }}-svc
  labels:
    {{- include "arthas-center.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.server.type }}
  ports:
    - port: {{ .Values.service.server.http.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq "NodePort" .Values.service.server.type }}
      nodePort: {{ .Values.service.server.http.nodePort }}
      {{- end }}
    - port: {{ .Values.service.server.ws.port }}
      targetPort: ws
      protocol: TCP
      name: ws
      {{- if eq "NodePort" .Values.service.server.type }}
      nodePort: {{ .Values.service.server.ws.nodePort }}
      {{- end }}
  selector:
    {{- include "arthas-center.selectorLabels" . | nindent 4 }}
